### PR TITLE
Switching from xUnit to NUnit

### PR DESCRIPTION
**Pull request by arlm**
The xUnit tests do not work (they don't even get loaded) on Visual Studio for Mac. Switching to NUnit so that it can work on both platforms.

### CODE REVIEW

**Comment by b3b00** [comment]
Hello Alexandre, i appreciate your contribution. Nevertheless you choose to merge to master but dev was the good target. Could you change this please. And I have to check if appveyor CI is still OK after switching to NUnit

**Comment by arlm** [comment]
Is appveyor integrated here? I mean, shouldn't it check automatically when I propose a pull request?

**Comment by b3b00** [comment]
yes it should but did not trigger I dont know why. I am awqy from mh computer, will check this in 2 days. thanks again

**Comment by b3b00** [comment]
discarded

**Comment by arlm** [comment]
OK. No problem. Just to let you know. The tests are not even loaded on the Visual Studio for Mac

**Pull request merged**
